# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localhost

  adminer:
    image: adminer
    ports:
      - 8080:8080